name: first workflow

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4

            - name: welcome message, cat readme
              run: | #pipe is used to run multiple commands in 1line.
                 echo "welcome"
                 ls -lrt
                 cat README.md
                  
            
            # - name: list files
            #   run: ls

            # - name: read file
            #   run: cat README.md