name: first workflow

on: push

jobs:
  first-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: welcome message, cat readme
        run: |  # Pipe is used to run multiple commands in one line.
          echo "welcome"
          ls -lrt
          cat README.md

  first-job-2:
    needs: first-job-1
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: add permissions to file
        run: |
          chmod 777 README.md
          ls -l README.md
          # mv README.md readme.md
      
      - name: list the file
        run: ls -ltr
      # Uncomment and modify the following section if needed
      # - name: edit readme file
      #   run: |
      #     mv README.md readme.md

  first-job-3:
    needs: first-job-2
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: rename the file
        run: |
        ls -lrt
        mv README.md readme.md

      # Uncomment and modify the following sections if needed
      # - name: list files
      #   run: ls

      # - name: read file
      #   run: cat README.md
