name: first workflow

on: push

jobs:
    first-job-1:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4

            - name: welcome message, cat readme
              run: | #pipe is used to run multiple commands in 1line.
                 echo "welcome"
                 ls -lrt
                 cat README.md
    first-job-2:
      runs-on: ubuntu-latest
      steps:
        - name: checkout repo
          uses: actions/checkout@v4
        - name: edit readme file
          run: |-
          mv README.md readme.md
    first-job-3:
      runs-on: ubuntu-latest
      steps:
        - name: list the file
          run: |
          ls -ltr

                  
            
            # - name: list files
            #   run: ls

            # - name: read file
            #   run: cat README.md