name: workflow 2

on: push

jobs:
    workflow_job_2:
        runs-on: ubuntu-latest
        steps:
        - name: welcome messgae
          run: echo "welcome!"

        - name: list the files in repo.
          run: pwd

        - name: checkout branch
          uses: actions/checkout@v4
          with:
            ref: main
 
        - run:
            ls -lrt
            cat README.md



  